FROM public.ecr.aws/docker/library/python:3.10-slim

WORKDIR /app

 # 只复制依赖文件
COPY requirements-api.txt /app/

ARG AWS_REGION=cn-northwest-1
ENV AWS_REGION=${AWS_REGION}

# Print the AWS_REGION for verification
RUN echo "Current AWS Region: $AWS_REGION"

# Update apt sources based on AWS region
RUN if [ "$AWS_REGION" = "cn-north-1" ] || [ "$AWS_REGION" = "cn-northwest-1" ]; then \
        echo "Using Tsinghua mirrors for apt..." && \
        rm -rf /etc/apt/sources.list.d/debian.sources && \
        echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
        echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
        echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
        echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list; \
    fi
    
# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    make \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies using the appropriate PyPI source based on AWS region
RUN if [ "$AWS_REGION" = "cn-north-1" ] || [ "$AWS_REGION" = "cn-northwest-1" ]; then \
        pip3 install -r requirements-api.txt -i https://pypi.tuna.tsinghua.edu.cn/simple; \
    else \
        pip3 install -r requirements-api.txt; \
    fi

COPY . /app/

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--workers" , "4"]
