"""
Language configuration for the Generative BI application.
This file contains translations for UI elements in both English and Chinese.
"""

# Dictionary of translations
translations = {
    "en": {
        # Model Provider page - Embedding Models tab
        "embedding_model_management": "Embedding Model Management",
        "select_embedding_model": "Select Embedding Model",
        "select_embedding_model_placeholder": "Select an embedding model",
        "select_embedding_model_info": "Please select an embedding model from the dropdown above or create a new one.",
        "create_new_embedding_model": "Create New Embedding Model",
        "new_embedding_model": "New Embedding Model",
        "model_name": "Model Name",
        "model_name_help": "A unique name for this embedding model",
        "platform": "Platform",
        "model_name_endpoint": "Model Name/Endpoint",
        "model_name_endpoint_help": "The model ID or endpoint name",
        "aws_region": "AWS Region",
        "bedrock_region_help": "The AWS region for Bedrock",
        "sagemaker_region_help": "The AWS region for SageMaker",
        "vector_dimension": "Vector Dimension",
        "vector_dimension_help": "The dimension of the embedding vectors",
        "input_format_optional": "Input Format (Optional)",
        "input_format": "Input Format",
        "input_format_help": "JSON format for the input payload. Use INPUT_TEXT as placeholder for the text.",
        "api_url_help": "The URL for the API endpoint",
        "api_key_optional": "API Key (Optional)",
        "api_key": "API Key",
        "api_key_help": "The API key for authentication",
        "test_text": "Test Text",
        "test_text_default": "This is a test text for embedding generation",
        "test_text_help": "Enter text to test the embedding model",
        "test_connection": "Test Connection",
        "dimension": "Dimension",
        "embedding_sample": "Embedding sample:",
        "empty_embedding_warning": "No embedding values returned. The model may have returned an empty embedding.",
        "add_embedding_model": "Add Embedding Model",
        "model_name_required": "Model name is required",
        "model_name_endpoint_required": "Model name/endpoint is required",
        "aws_region_required": "AWS region is required",
        "api_url_required": "API URL is required",
        "embedding_model_added": "Embedding model {} added successfully",
        "update_embedding_model": "Update Embedding Model",
        "model_id": "Model ID",
        "update_embedding_model_btn": "Update Embedding Model",
        "delete_embedding_model": "Delete Embedding Model",
        "model_not_found": "No model selected or model could not be loaded",
        
        # Model Provider page - Global Settings tab
        "global_settings": "Global Settings",
        "global_settings_description": "Configure default settings for the application",
        "default_llm_model": "Default LLM Model",
        "select_default_llm": "Select Default LLM Model",
        "default_llm_help": "This model will be used as the default for all operations",
        "default_embedding_model": "Default Embedding Model",
        "select_default_embedding": "Select Default Embedding Model",
        "default_embedding_help": "This model will be used for all embedding operations",
        "default_profile": "Default Profile",
        "select_default_profile": "Select Default Profile",
        "default_profile_help": "This profile will be loaded by default when the application starts",
        "save_global_settings": "Save Global Settings",
        "global_settings_updated": "Global settings updated successfully",
        "changes_effect_next_restart": "The changes will take effect on the next application restart",
        
        # Model Provider page - Tab names
        "llm_models_tab": "LLM Models",
        "embedding_models_tab": "Embedding Models",
        "global_settings_tab": "Global Settings",
        # Common UI elements
        "app_title": "Generative BI",
        "page_title": "Generative BI Playground",
        "current_username": "Current Username",
        "assistant_intro": "I'm the Generative BI assistant. Please **ask a question** or **select a sample question** below to start.",
        "no_profile_warning": "You should first create a database connection and then create a data profile",
        "welcome_title": "Welcome to Generative BI using RAG on Amazon Web Services!👋",
        "select_demo": "Select a demo above.",
        "select_connection_sidebar": "Please select connection in the left sidebar.",
        
        # Model Management page
        "model_management_title": "Model Management",
        "model_select": "Model Select",
        "select_model": "Please Select Model...",
        "create_new_model": "Create New Model Conf",
        "new_model": "New Model",
        "model_type": "Model Type",
        "sagemaker_endpoint_name": "SageMaker Endpoint Name",
        "sagemaker_endpoint_region": "SageMaker Endpoint Region",
        "prompt_template": "Prompt Template",
        "prompt_template_placeholder": "Enter prompt template, need contain SYSTEM_PROMPT Placeholder and USER_PROMPT Placeholder. \n For Example: SYSTEM_PROMPT<|im_start|>user\nUSER_PROMPT<|im_end|>\n<|im_start|>assistant\n",
        "prompt_template_help": "Enter prompt template, need contain SYSTEM_PROMPT Placeholder and USER_PROMPT Placeholder",
        "input_payload": "Mode Input Payload",
        "input_payload_placeholder": "Enter input payload in JSON dumps str, The input text use INPUT Placeholder.",
        "input_payload_help": "Enter input payload in JSON dumps str, The input text use INPUT Placeholder",
        "output_format": "Model Output Format",
        "output_format_placeholder": "Enter output format, The output value name is response. For Example: response[0]['generated_text']",
        "output_format_help": "Enter output format, The output value name is response",
        "model_connection_test": "Model Connection Test",
        "add_connection": "Add Connection",
        "update_model_connection": "Update Model Connection",
        "delete_model_connection": "Delete Model Connection",
        "connected_successfully": "Connected successfully!",
        "failed_to_connect": "Failed to connect!",
        "added_successfully": "{} added successfully!",
        "updated_successfully": "{} updated successfully!",
        "deleted_successfully": "{} deleted successfully!",
        "prompt_added_successfully": "Prompt added successfully!",
        "profiles_update_successfully": "profiles update successfully!",
        "prompt_delete_successfully": "Prompt delete successfully!",
        "api_model_name": "API Model Name",
        "api_url": "API URL",
        "api_header": "API Header",
        "api_header_help": "Enter API Header, json format",
        "bedrock_anthropic_model_id": "BedRock Anthropic Model ID",
        "bedrock_anthropic_model_region": "BedRock Anthropic Model Region",
        "bedrock_amazon_nova_model_id": "BedRock Amazon Nova Model ID",
        "bedrock_amazon_nova_model_region": "BedRock Amazon Nova Model Region",
        "update_model_connection_title": "Update Model Connection",
        "input_payload_json_format": "The Input Payload is Json format str, Parameters can be modified, but do not change the format",
        "required_error": "{} is required!",
        "update_prompt": "Update Prompt...",
        "sagemaker": "Sagemaker",
        "bedrock_api": "Bedrock API",
        "br_client_api": "BR Client API",
        "bedrock_anthropic_model": "BedRock Anthropic Model",
        "bedrock_amazon_model": "BedRock Amazon Model",
        "embedding_model_test": "Embedding Model Test",
        
        # User Authorization page
        "user_authorization_title": "User Authorization Management",
        "view_user_profile_map": "View User Profile Map",
        "add_new_user_map": "Add New User Map",
        "select_data_profile": "Select Data Profile",
        "select_all": "Select All",
        "clear": "Clear",
        "delete": "Delete",
        "save": "Save",
        "submit": "Submit",
        "user_id": "User Id",
        "user_removed": "Remove User {} access {} ",
        "user_authorized": "Authorized User {} access {} ",
        "valid_user_profile_error": "Please input a valid user ID and select at least 1 profile.",
        
        # Login page
        "login_title": "Login",
        "username": "Username",
        "password": "Password",
        "login_button": "Login",
        "login_error": "Username/password is incorrect",
        "login_warning": "Please enter your username and password",
        
        # Data Connection Management page
        "data_connection_title": "Data Connection Management",
        "connection_name": "Connection Name",
        "db_type": "Database Type",
        "host": "Host",
        "port": "Port",
        "database": "Database",
        "test_connection": "Test Connection",
        "add_connection": "Add Connection",
        "connection_list": "Connection List",
        "delete_connection": "Delete Connection",
        "connection_success": "Connection successful!",
        "connection_failed": "Connection failed: {}",
        "connection_added": "Connection added successfully!",
        "connection_deleted": "Connection deleted successfully!",
        "confirm_delete": "Are you sure you want to delete this connection?",
        "update_connection": "Update Connection",
        "new_connection": "New Database Connection",
        "update_connection_title": "Update Database Connection",
        "comment": "Enter comment",
        "create_new": "Create new...",
        "select_connection": "Please select database connection...",
        
        # Settings sidebar
        "settings_title": "Settings",
        "data_profile": "Data Profile",
        "choose_model": "Choose your model",
        "using_rag": "Using RAG from Q/A Embedding",
        "visualize_results": "Visualize Results",
        "intent_ner": "Intent NER",
        "agent_cot": "Agent COT",
        "explain_gen_process": "Explain Generation Process",
        "answer_with_insights": "Answer With Insights",
        "gen_suggested_questions": "Generate Suggested Questions",
        "auto_correcting_sql": "Auto Correcting SQL",
        "show_token_cost": "Show Token Cost",
        "context_window": "Multiple Rounds of Context Window",
        "clean_history": "Clean History",
        "language": "Language",
        
        # Status messages
        "query_context_understanding": "Query Context Understanding",
        "query_context_rewrite_completed": "Query Context Rewrite Completed",
        "query_not_supported": "Your query statement is currently not supported by the system",
        "entity_retrieval": "Performing Entity retrieval...",
        "entity_retrieval_completed": "Entity Retrieval Completed: {} entities retrieved",
        "qa_retrieval": "Performing QA retrieval...",
        "qa_retrieval_completed": "QA Retrieval Completed: {} entities retrieved",
        "generating_sql": "Generating SQL...",
        "generating_sql_done": "Generating SQL Done",
        "generating_explanations": "Generating explanations...",
        "generating_explanations_done": "Generating explanations Done",
        "intent_recognition": "Performing intent recognition...",
        "intent_recognition_completed": "Intent Recognition Completed: This is a **{}** question",
        "execute_sql": "Execute SQL...",
        "execute_sql_done": "Execute SQL Done",
        "sql_error_info": "The SQL Error Info",
        "generating_sql_again": "Generating SQL Again...",
        "generating_data_summarize": "Generating data summarize...",
        "agent_cot_retrieval": "Agent Cot retrieval...",
        "agent_cot_retrieval_completed": "Agent Cot Retrieval Completed",
        "agent_task_split": "Agent Task split...",
        "agent_task_split_completed": "Agent Task Split Completed",
        "multiple_sql_generated": "Multiple SQL generated...",
        "multiple_sql_generated_completed": "Multiple SQL Generated Completed",
        "error_info": "The Error Info Please Check",
        "further_ask": "You might want to further ask:",
        "generating_suggested_questions": "Generating suggested questions...",
        
        # Buttons
        "upvote": "👍 Upvote (save as embedding for retrieval)",
        "downvote": "👎 Downvote",
        
        # Chart visualization
        "choose_chart_type": "Choose the chart type",
        "choose_x_axis": "Choose x-axis column",
        "choose_y_axis": "Choose y-axis column",
        
        # Index Management page
        "index_management_title": "Index Management",
        "view_samples": "View Samples",
        "add_new_sample": "Add New Sample",
        "sample_search": "Sample Search",
        "batch_insert_samples": "Batch Insert Samples",
        "regression_test": "Regression Test",
        "max_display_info": "The display page can show a maximum of 5000 pieces of data",
        "edit": "Edit ",
        "delete": "Delete ",
        "question": "Question",
        "answer_sql": "Answer(SQL)",
        "add_sql_info": "Add SQL Info",
        "sample_added": "Sample added",
        "update_index": "Update Index",
        "updating_index": "Update Index ...",
        "input_valid_qa": "please input valid question and answer",
        "question_search": "Question Search",
        "question_retrieve_number": "Question Retrieve Number",
        "search": "Search",
        "batch_insert_info": "This page support CSV or Excel files batch insert sql samples.",
        "column_name_info": "**The Column Name need contain 'question' and 'sql'**",
        "choose_files": "Choose CSV or Excel files",
        "upload_sql_files": "Upload SQL Example Files",
        "processing_file": "Processing file {0} of {1}: {2}",
        "batch_insert_progress": "batch insert {0} entity in progress. Please wait.",
        "uploaded_successfully": "{0} uploaded successfully!",
        "total_samples_test": "Total [{0}] samples to be tested !",
        "choose_model": "Choose your model",
        "test_all": "Test All",
        "regression_testing_result": "Regression Testing Result:",
        "testing_completed": "Testing Completed",
        "sample_deleted": "Sample {0} deleted.",
        "sample_updated": "Sample updated successfully!",
        "unsupported_file_type": "Unsupported file type: {0}",
        "columns_need_contain": "The columns need contains question and sql",
        
        # Prompt Management page
        "prompt_management_title": "Prompt Management",
        "prompt_type": "Prompt Type",
        "select_prompt_type": "Please select a prompt type",
        "llm_model": "LLM Model",
        "select_model": "Please select a model",
        "custom_env_variables": "Custom Environment Variables",
        "environment_name": "Environment Name: ",
        "environment_value": ", Environment Value:",
        "system_prompt": "System Prompt",
        "user_prompt": "User Prompt",
        "save_prompt": "Save",
        "saved_prompt": "Saved",
        "failed_save_prompts": "Failed to save prompts  \nMissing syntax in System Prompt: {}  \nMissing syntax in User Prompt: {}",
        
        # Data Profile Management page
        "data_profile_title": "Data Profile Management",
        "my_data_profiles": "My Data Profiles",
        "create_new_profile": "Create new profile...",
        "create_new_data_profile": "Create New Data Profile",
        "update_data_profile": "Update Data Profile",
        "profile_name": "Profile Name",
        "schema_name": "Schema Name",
        "select_tables": "Select tables included in this profile",
        "create_profile": "Create Profile",
        "update_profile": "Update Profile",
        "delete_profile": "Delete Profile",
        "profile_created": "Profile created.",
        "profile_updated": "Profile updated. Please click \"Fetch table definition\" button to continue.",
        "profile_deleted": "{} deleted successfully!",
        "fetch_table_definition": "Fetch table definition",
        "creating_profile": "Creating profile...",
        "fetching": "fetching...",
        "select_at_least_one_table": "Please select at least one table.",
        "tables_not_exist": "Some tables defined in this profile are not existing in the database.",
        "connection_not_found": "connection not found",
        "enable_rls": "Enable Row Level Security",
        "rls_help": "Row level security: Replacing the generated SQL with user-aware filter. Support MySQL and Clickhouse.",
        "rls_config": "Row Level Security Filter using YAML",
        "invalid_rls_config": "Invalid row level security config.",
        "rls_placeholder": """tables:
      - table_name: table_a
        columns:
          - column_name: username
            column_value: $login_user.username""",
        "comments_placeholder": """Your comments for this data profile.
You can add sample questions after samples, one question one line.
Examples:
Your sample question 1
Your sample question 2""",
        "comments": "Comments (add sample questions after Examples:, one question one line)",
        "select_profile": "Please select data profile...",
        
        # Schema Description Management page
        "schema_management_title": "Schema Management",
        "tables": "Tables",
        "select_table": "Please select a table",
        "table_description": "Table Description: {}",
        "table_annotation": "Table Annotation",
        "column_annotation": "Column Annotation",
        "column_annotation_help": """For example CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique identifier for each employee',
    name VARCHAR(100) NOT NULL COMMENT 'Employee name', 
    position VARCHAR(50) NOT NULL COMMENT 'Position, 2 possible values: 'Engineer', 'Manager'',
    salary DECIMAL(10, 2) COMMENT 'Salary in USD, e.g. 1000.00',
    date DATE NOT NULL COMMENT 'Date of joining the company'
    ...
);
    """,
        "save": "Save",
        "saved": "Saved.",
        "select_data_profile_sidebar": "Please select data profile in the left sidebar.",
        
        # Prompt Environment Management page
        "prompt_environment_title": "Prompt Environment Management",
        "environment_name_label": "Environment Name",
        "environment_value_label": "Environment Value",
        "submit_button": "Submit",
        "cancel_button": "Cancel",
        "environment_updated": "Environment updated successfully!",
        "environment_deleted": "Environment deleted:",
        "environment_view_tab": "Environment View",
        "environment_edit_tab": "Environment Edit",
        "edit_button": "Edit",
        "delete_button": "Delete",
        "add_environment_button": "Add Prompt Environment",
        "system_environment_error": "Please use another environment name. This is a system environment name.",
        "environment_name_format_error": "Please check environment name format, for example: {year}",
    },
    "zh": {
        # Model Provider page - Embedding Models tab
        "embedding_model_management": "嵌入模型管理",
        "select_embedding_model": "选择嵌入模型",
        "select_embedding_model_placeholder": "选择一个嵌入模型",
        "select_embedding_model_info": "请从上方下拉菜单选择一个嵌入模型或创建一个新模型。",
        "create_new_embedding_model": "创建新嵌入模型",
        "new_embedding_model": "新嵌入模型",
        "model_name": "模型名称",
        "model_name_help": "为此嵌入模型提供一个唯一名称",
        "platform": "平台",
        "model_name_endpoint": "模型名称/端点",
        "model_name_endpoint_help": "模型ID或端点名称",
        "aws_region": "AWS区域",
        "bedrock_region_help": "Bedrock的AWS区域",
        "sagemaker_region_help": "SageMaker的AWS区域",
        "vector_dimension": "向量维度",
        "vector_dimension_help": "嵌入向量的维度",
        "input_format_optional": "输入格式（可选）",
        "input_format": "输入格式",
        "input_format_help": "输入负载的JSON格式。使用INPUT_TEXT作为文本的占位符。",
        "api_url_help": "API端点的URL",
        "api_key_optional": "API密钥（可选）",
        "api_key": "API密钥",
        "api_key_help": "用于认证的API密钥",
        "test_text": "测试文本",
        "test_text_default": "这是用于生成嵌入的测试文本",
        "test_text_help": "输入文本以测试嵌入模型",
        "test_connection": "测试连接",
        "dimension": "维度",
        "embedding_sample": "嵌入样本：",
        "empty_embedding_warning": "未返回嵌入值。模型可能返回了空嵌入。",
        "add_embedding_model": "添加嵌入模型",
        "model_name_required": "模型名称为必填项",
        "model_name_endpoint_required": "模型名称/端点为必填项",
        "aws_region_required": "AWS区域为必填项",
        "api_url_required": "API URL为必填项",
        "embedding_model_added": "嵌入模型{}添加成功",
        "update_embedding_model": "更新嵌入模型",
        "model_id": "模型ID",
        "update_embedding_model_btn": "更新嵌入模型",
        "delete_embedding_model": "删除嵌入模型",
        "model_not_found": "未选择模型或无法加载模型",
        
        # Model Provider page - Global Settings tab
        "global_settings": "全局设置",
        "global_settings_description": "配置应用程序的默认设置",
        "default_llm_model": "默认LLM模型",
        "select_default_llm": "选择默认LLM模型",
        "default_llm_help": "此模型将用作所有操作的默认模型",
        "default_embedding_model": "默认嵌入模型",
        "select_default_embedding": "选择默认嵌入模型",
        "default_embedding_help": "此模型将用于所有嵌入操作",
        "default_profile": "默认配置文件",
        "select_default_profile": "选择默认配置文件",
        "default_profile_help": "应用程序启动时将默认加载此配置文件",
        "save_global_settings": "保存全局设置",
        "global_settings_updated": "全局设置更新成功",
        "changes_effect_next_restart": "更改将在下次应用程序重启时生效",
        
        # Model Provider page - Tab names
        "llm_models_tab": "LLM模型",
        "embedding_models_tab": "嵌入模型",
        "global_settings_tab": "全局设置",
        # Common UI elements
        "app_title": "生成式商业智能",
        "page_title": "生成式商业智能平台",
        "current_username": "当前用户名",
        "assistant_intro": "我是生成式商业智能助手。请**提出问题**或**选择下方的示例问题**开始。",
        "no_profile_warning": "您应该先创建数据库连接，然后创建数据配置文件",
        "welcome_title": "欢迎使用基于亚马逊云科技RAG的生成式商业智能!👋",
        "select_demo": "在上方选择演示。",
        "select_connection_sidebar": "请在左侧边栏选择连接。",
        
        # Model Management page
        "model_management_title": "模型管理",
        "model_select": "模型选择",
        "select_model": "请选择模型...",
        "create_new_model": "创建新模型配置",
        "new_model": "新模型",
        "model_type": "模型类型",
        "sagemaker_endpoint_name": "SageMaker端点名称",
        "sagemaker_endpoint_region": "SageMaker端点区域",
        "prompt_template": "提示词模板",
        "prompt_template_placeholder": "输入提示词模板，需要包含SYSTEM_PROMPT占位符和USER_PROMPT占位符。\n例如：SYSTEM_PROMPT<|im_start|>user\nUSER_PROMPT<|im_end|>\n<|im_start|>assistant\n",
        "prompt_template_help": "输入提示词模板，需要包含SYSTEM_PROMPT占位符和USER_PROMPT占位符",
        "input_payload": "模型输入负载",
        "input_payload_placeholder": "以JSON格式输入负载，输入文本使用INPUT占位符。",
        "input_payload_help": "以JSON格式输入负载，输入文本使用INPUT占位符",
        "output_format": "模型输出格式",
        "output_format_placeholder": "输入输出格式，输出值名称为response。例如：response[0]['generated_text']",
        "output_format_help": "输入输出格式，输出值名称为response",
        "model_connection_test": "模型连接测试",
        "add_connection": "添加连接",
        "update_model_connection": "更新模型连接",
        "delete_model_connection": "删除模型连接",
        "connected_successfully": "连接成功！",
        "failed_to_connect": "连接失败！",
        "added_successfully": "{} 添加成功！",
        "updated_successfully": "{} 更新成功！",
        "deleted_successfully": "{} 删除成功！",
        "prompt_added_successfully": "提示词添加成功！",
        "profiles_update_successfully": "配置文件更新成功！",
        "prompt_delete_successfully": "提示词删除成功！",
        "api_model_name": "API模型名称",
        "api_url": "API URL",
        "api_header": "API头信息",
        "api_header_help": "输入API头信息，JSON格式",
        "bedrock_anthropic_model_id": "BedRock Anthropic模型ID",
        "bedrock_anthropic_model_region": "BedRock Anthropic模型区域",
        "bedrock_amazon_nova_model_id": "BedRock Amazon Nova模型ID",
        "bedrock_amazon_nova_model_region": "BedRock Amazon Nova模型区域",
        "update_model_connection_title": "更新模型连接",
        "input_payload_json_format": "输入负载为JSON格式字符串，参数可以修改，但不要改变格式",
        "required_error": "{} 是必填项！",
        "update_prompt": "更新提示词...",
        "sagemaker": "SageMaker",
        "bedrock_api": "Bedrock API",
        "br_client_api": "BR Client API",
        "bedrock_anthropic_model": "BedRock Anthropic模型",
        "bedrock_amazon_model": "BedRock Amazon模型",
        "delete_prompt": "删除提示词...",
        "embedding_model_test": "嵌入模型测试",
        
        # User Authorization page
        "user_authorization_title": "用户授权管理",
        "view_user_profile_map": "查看用户配置文件映射",
        "add_new_user_map": "添加新用户映射",
        "select_data_profile": "选择数据配置文件",
        "select_all": "全选",
        "clear": "清除",
        "delete": "删除",
        "save": "保存",
        "submit": "提交",
        "user_id": "用户ID",
        "user_removed": "已移除用户 {} 对 {} 的访问权限",
        "user_authorized": "已授权用户 {} 访问 {}",
        "valid_user_profile_error": "请输入有效的用户ID并至少选择1个配置文件。",
        
        # Settings sidebar
        "settings_title": "设置",
        "data_profile": "数据配置文件",
        "choose_model": "选择模型",
        "using_rag": "使用问答嵌入RAG",
        "visualize_results": "可视化结果",
        "intent_ner": "意图命名实体识别",
        "agent_cot": "智能体思维链",
        "explain_gen_process": "解释生成过程",
        "answer_with_insights": "回答包含洞察",
        "gen_suggested_questions": "生成建议问题",
        "auto_correcting_sql": "自动纠正SQL",
        "show_token_cost": "显示Token消耗",
        "context_window": "多轮对话上下文窗口",
        "clean_history": "清除历史",
        "language": "语言",
        
        # Status messages
        "query_context_understanding": "查询上下文理解中",
        "query_context_rewrite_completed": "查询上下文重写完成",
        "query_not_supported": "系统当前不支持您的查询语句",
        "entity_retrieval": "正在执行实体检索...",
        "entity_retrieval_completed": "实体检索完成：检索到{}个实体",
        "qa_retrieval": "正在执行问答检索...",
        "qa_retrieval_completed": "问答检索完成：检索到{}个实体",
        "generating_sql": "正在生成SQL...",
        "generating_sql_done": "SQL生成完成",
        "generating_explanations": "正在生成解释...",
        "generating_explanations_done": "解释生成完成",
        "intent_recognition": "正在执行意图识别...",
        "intent_recognition_completed": "意图识别完成：这是一个**{}**问题",
        "execute_sql": "执行SQL中...",
        "execute_sql_done": "SQL执行完成",
        "sql_error_info": "SQL错误信息",
        "generating_sql_again": "再次生成SQL...",
        "generating_data_summarize": "正在生成数据摘要...",
        "agent_cot_retrieval": "智能体思维链检索中...",
        "agent_cot_retrieval_completed": "智能体思维链检索完成",
        "agent_task_split": "智能体任务拆分中...",
        "agent_task_split_completed": "智能体任务拆分完成",
        "multiple_sql_generated": "多SQL生成中...",
        "multiple_sql_generated_completed": "多SQL生成完成",
        "error_info": "请检查错误信息",
        "further_ask": "您可能想进一步询问：",
        "generating_suggested_questions": "正在生成建议问题...",
        
        # Buttons
        "upvote": "👍 点赞（保存为检索嵌入）",
        "downvote": "👎 踩",
        
        # Chart visualization
        "choose_chart_type": "选择图表类型",
        "choose_x_axis": "选择X轴列",
        "choose_y_axis": "选择Y轴列",
        
        # Chart types
        "table": "表格",
        "bar": "柱状图",
        "line": "折线图",
        "pie": "饼图",
        
        # Input placeholder
        "query_placeholder": "在此输入您的查询...",
        
        # Login page
        "login_title": "登录",
        "username": "用户名",
        "password": "密码",
        "login_button": "登录",
        "login_error": "用户名/密码不正确",
        "login_warning": "请输入您的用户名和密码",
        
        # Data Connection Management page
        "data_connection_title": "数据连接管理",
        "connection_name": "连接名称",
        "db_type": "数据库类型",
        "host": "主机",
        "port": "端口",
        "database": "数据库",
        "test_connection": "测试连接",
        "add_connection": "添加连接",
        "connection_list": "连接列表",
        "delete_connection": "删除连接",
        "connection_success": "连接成功！",
        "connection_failed": "连接失败：{}",
        "connection_added": "连接添加成功！",
        "connection_deleted": "连接删除成功！",
        "confirm_delete": "您确定要删除此连接吗？",
        "update_connection": "更新连接",
        "new_connection": "新建数据库连接",
        "update_connection_title": "更新数据库连接",
        "comment": "输入备注",
        "create_new": "创建新连接...",
        "select_connection": "请选择数据库连接...",
        
        # Index Management page
        "index_management_title": "索引管理",
        "view_samples": "查看样本",
        "add_new_sample": "添加新样本",
        "sample_search": "样本搜索",
        "batch_insert_samples": "批量插入样本",
        "regression_test": "回归测试",
        "max_display_info": "显示页面最多可显示5000条数据",
        "edit": "编辑 ",
        "delete": "删除 ",
        "question": "问题",
        "answer_sql": "回答(SQL)",
        "add_sql_info": "添加SQL信息",
        "sample_added": "样本已添加",
        "update_index": "更新索引",
        "updating_index": "正在更新索引...",
        "input_valid_qa": "请输入有效的问题和答案",
        "question_search": "问题搜索",
        "question_retrieve_number": "问题检索数量",
        "search": "搜索",
        "batch_insert_info": "此页面支持CSV或Excel文件批量插入SQL样本。",
        "column_name_info": "**列名需要包含'question'和'sql'**",
        "choose_files": "选择CSV或Excel文件",
        "upload_sql_files": "上传SQL示例文件",
        "processing_file": "正在处理文件 {0}/{1}: {2}",
        "batch_insert_progress": "批量插入 {0} 实体进行中。请稍候。",
        "uploaded_successfully": "{0} 上传成功！",
        "total_samples_test": "共有 [{0}] 个样本待测试！",
        "choose_model": "选择您的模型",
        "test_all": "测试全部",
        "regression_testing_result": "回归测试结果：",
        "testing_completed": "测试完成",
        "sample_deleted": "样本 {0} 已删除。",
        "sample_updated": "样本更新成功！",
        "unsupported_file_type": "不支持的文件类型：{0}",
        "columns_need_contain": "列需要包含question和sql",
        
        # Data Profile Management page
        "data_profile_title": "数据配置文件管理",
        "my_data_profiles": "我的数据配置文件",
        "create_new_profile": "创建新配置文件...",
        "create_new_data_profile": "创建新数据配置文件",
        "update_data_profile": "更新数据配置文件",
        "profile_name": "配置文件名称",
        "schema_name": "模式名称",
        "select_tables": "选择此配置文件中包含的表",
        "create_profile": "创建配置文件",
        "update_profile": "更新配置文件",
        "delete_profile": "删除配置文件",
        "profile_created": "配置文件已创建。",
        "profile_updated": "配置文件已更新。请点击\"获取表定义\"按钮继续。",
        "profile_deleted": "{} 已成功删除！",
        "fetch_table_definition": "获取表定义",
        "creating_profile": "正在创建配置文件...",
        "fetching": "正在获取...",
        "select_at_least_one_table": "请至少选择一个表。",
        "tables_not_exist": "此配置文件中定义的某些表在数据库中不存在。",
        "connection_not_found": "未找到连接",
        "enable_rls": "启用行级安全",
        "rls_help": "行级安全：用用户感知过滤器替换生成的SQL。支持MySQL和Clickhouse。",
        "rls_config": "使用YAML的行级安全过滤器",
        "invalid_rls_config": "无效的行级安全配置。",
        "rls_placeholder": """tables:
      - table_name: table_a
        columns:
          - column_name: username
            column_value: $login_user.username""",
        "comments_placeholder": """您对此数据配置文件的注释。
您可以在示例后添加示例问题，一行一个问题。
示例：
您的示例问题1
您的示例问题2""",
        "comments": "注释（在\"Examples:\"后添加示例问题，一行一个问题）",
        "select_profile": "请选择数据配置文件...",
        
        # Schema Description Management page
        "schema_management_title": "元数据管理",
        "tables": "表",
        "select_table": "请选择一个表",
        "table_description": "表描述: {}",
        "table_annotation": "表注释",
        "column_annotation": "列注释",
        "column_annotation_help": """例如 CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '每个员工的唯一标识符',
    name VARCHAR(100) NOT NULL COMMENT '员工姓名', 
    position VARCHAR(50) NOT NULL COMMENT '职位，2个可能的值：\"工程师\"，\"经理\"',
    salary DECIMAL(10, 2) COMMENT '薪资（美元），例如 1000.00',
    date DATE NOT NULL COMMENT '入职公司的日期'
    ...
);
    """,
        "save": "保存",
        "saved": "已保存。",
        "select_data_profile_sidebar": "请在左侧边栏选择数据配置文件。",
        
        # Prompt Environment Management page
        "prompt_environment_title": "提示词环境管理",
        "environment_name_label": "环境名称",
        "environment_value_label": "环境值",
        "submit_button": "提交",
        "cancel_button": "取消",
        "environment_updated": "环境更新成功！",
        "environment_deleted": "环境已删除：",
        "environment_view_tab": "环境查看",
        "environment_edit_tab": "环境编辑",
        "edit_button": "编辑",
        "delete_button": "删除",
        "add_environment_button": "添加提示词环境",
        "system_environment_error": "请使用其他环境名称。这是系统环境名称。",
        "environment_name_format_error": "请检查环境名称格式，例如：{year}",
        
        # Agent CoT Management page
        "agent_cot_management_title": "智能体思维链管理",
        "view_cot_samples": "查看思维链样本",
        "add_new_cot_sample": "添加新思维链样本",
        "cot_sample_search": "思维链样本搜索",
        "modify_sql_value": "修改SQL值",
        "query": "查询",
        "answer": "回答(SQL)",
        "submit": "提交",
        "cancel": "取消",
        "sample_updated": "样本更新成功！",
        "cot_info_deleted": "样本 {} 已删除。",
        "add_cot_info": "添加思维链信息",
        "cot_info_added": "样本已添加",
        "entity_search": "实体搜索",
        "entity_retrieve_number": "实体检索数量",
        
        # Entity Management page
        "entity_management_title": "实体管理",
        "view_entity_info": "查看实体信息",
        "add_metrics_entity": "添加指标实体",
        "add_dimension_entity": "添加维度实体",
        "entity_search": "实体搜索",
        "batch_metrics_entity": "批量指标实体",
        "batch_dimension_entity": "批量维度实体",
        "entity": "实体",
        "comment": "注释",
        "table": "表",
        "column": "列",
        "dimension_value": "维度值",
        "entity_search_label": "实体搜索",
        "entity_retrieve_number": "实体检索数量",
        "search_button": "搜索",
        "batch_metrics_info": "此页面支持CSV或Excel文件批量插入实体样本。",
        "batch_metrics_column_info": "**列名需要包含'entity'和'comment'**",
        "upload_metrics_files": "上传指标文件",
        "batch_dimension_info": "此页面支持CSV或Excel文件批量插入维度实体样本。",
        "batch_dimension_column_info": "**列名需要包含'entity'、'table'、'column'和'value'**",
        "upload_dimension_files": "上传维度文件",
        "dimension_load_type": "维度加载类型",
        "table_select": "表选择",
        "upload_file": "上传文件",
        "tables": "表",
        "download_insert_data": "下载插入数据为CSV",
        "batch_insert_dimension_entity": "批量插入维度实体",
        "processing_file": "正在处理文件 {0}/{1}: {2}",
        "batch_insert_progress": "批量插入进行中。已上传 {0} 个实体。请稍候。",
        "uploaded_successfully": "{0} 上传成功！",
        "sample_added": "样本已添加",
        "update_index": "更新索引",
        "please_input_valid": "请输入有效的问题和答案",
        "entity_table_info": "实体表信息",
        "submit_button": "提交",
        "cancel_button": "取消",
        "sample_updated": "样本更新成功！",
        "check_entity_format": "请检查实体信息格式！",
        "modify_entity_value": "修改实体值",
        
        # Agent CoT Management page
        "agent_cot_management_title": "智能体思维链管理",
        "view_cot_samples": "查看思维链样本",
        "add_new_cot_sample": "添加新思维链样本",
        "cot_sample_search": "思维链样本搜索",
        "modify_sql_value": "修改SQL值",
        "query": "查询",
        "answer": "回答(SQL)",
        "submit": "提交",
        "cancel": "取消",
        "sample_updated_successfully": "样本更新成功！",
        "cot_info_deleted": "样本 {} 已删除。",
        "add_cot_info": "添加思维链信息",
        "cot_info_added": "样本已添加",
        "entity_search": "实体搜索",
        "entity_retrieve_number": "实体检索数量",
        
        # Prompt Management page
        "prompt_management_title": "提示词管理",
        "prompt_type": "提示词类型",
        "select_prompt_type": "请选择提示词类型",
        "llm_model": "大语言模型",
        "select_model": "请选择模型",
        "custom_env_variables": "自定义环境变量",
        "environment_name": "环境名称: ",
        "environment_value": ", 环境值:",
        "system_prompt": "系统提示词",
        "user_prompt": "用户提示词",
        "save_prompt": "保存",
        "saved_prompt": "已保存",
        "failed_save_prompts": "保存提示词失败  \n系统提示词中缺少语法: {}  \n用户提示词中缺少语法: {}"
    }
}

def get_text(key, language):
    """
    Get the translated text for a given key and language.
    
    Args:
        key (str): The translation key
        language (str): The language code ('en' or 'zh')
        
    Returns:
        str: The translated text
    """
    if language not in translations:
        language = 'en'  # Default to English
    
    return translations[language].get(key, translations['en'].get(key, key))
