credentials:
  usernames:
    admin:
      email: zhihay@amazon.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: AWS
      password: $2b$12$63KcDNxFVV98oCWMjGNHbunZ9V1KsHOYG8Vt6UeNehTdH00KfVdTC # Set the password following instructions in README
cookie:
  expiry_days: 2
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
    - zhihay@amazon.com
