--- /home/ec2-user/guidance-for-generative-bi-v1.9.0/application/Dockerfile	2025-02-21 09:11:33.000000000 +0000
+++ /home/ec2-user/generative-bi-using-rag/application/Dockerfile	2025-04-08 11:56:26.366357722 +0000
@@ -1,4 +1,4 @@
-FROM public.ecr.aws/docker/library/python:3.10-slim
+FROM python:3.10-slim
 
 WORKDIR /app
 
